apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:invalid
    ports:
    - containerPort: 80
    env:
    - name: ENVIRONMENT
      valueFrom:
        configMapKeyRef:
          name: example-config
          key: environment
    - name: LOG_LEVEL
      valueFrom:
        configMapKeyRef:
          name: example-config
          key: log_level
