apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    app: redis
  namespace: default
spec:
  containers:
  - name: redis
    image: redis:7.0
    ports:
    - containerPort: 6379
    env:
    - name: REDIS_MODE
      valueFrom:
        configMapKeyRef:
          name: redis-config
          key: redis_mode
