name: Validate Kubernetes Manifests
on:
  push:
    branches: [ main ]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install kubectl
      run: |
        curl -LO https://dl.k8s.io/release/v1.28.0/bin/linux/amd64/kubectl
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/
    - name: Validate manifests
      run: |
        kubectl apply -k nginx-app --dry-run=client
        kubectl apply -k redis-app --dry-run=client
